### ISSUE TITLE
[Request] Add table for grading criteria in syllabus.md

### ISSUE THREAD

**Issue by aakash1104** [jlperona-teaching/ecs390-spring19#1]
Maybe adding a table that summarizes the grading criteria might be faster for students to look up weightage of assignments. 

Something like this(?):

| Grading                        | Weight            |Summary| 
| :-------------              | :------------- |  :------------- |
| *Attendance*                  | 60%                | (2 points/lecture) * 9 lectures  = 18 points|
| *Online Assignments*    | 30%                | (1 point/lecture) * 9 lectures  = 9 points|
| *Observation*                 | 10%                 | 3 points|
| **Total**                       |  **100%**       | **30 points** |

And then continue with a detailed description of what each of those mean (like what you've already done)

Sounds silly but I think this might help just in terms of summarizing the grading criteria. Of course, students would have to read the whole syllabus to understand everything but if someone wants to just confirm a grading criteria real quick, then this might help.

**Comment by jlperona** [comment]
Yup, that's useful. I had it for 154A, not sure why I didn't add it to 390. Ah well, it's there now.
