### ISSUE TITLE
[Request] Add TOC to syllabus.md

### ISSUE THREAD

**Issue by aakash1104** [jlperona-teaching/ecs390-spring19#2]
Adding a table of contents to the syllabus.md makes it easier to navigate around the file. You can hack up a Table of contents by adding in-document links at the top. If you have a heading called "grading", github markdown parses the tag as `#grading`. Use this to create an in-document hyperlink:

```
- [Grading](#grading)
    - [Attendance](#attendance)
    - [Assignments](#in-class-assignments)
```

**Comment by jlperona** [comment]
Thanks, slipped my mind. Fairly certain there's an auto-generator for Markdown that will generate this style of TOC for you but I haven't found it yet.

**Comment by aakash1104** [comment]
@jlperona There isn't a auto generated TOC Feature in Github Flavored MD. You can do this using Pandoc. Use the --toc flag while converting Markdown to PDF (or HTML), and you'll get a TOC.
